### ISSUE TITLE
Clean up the crontabs and scripts directory on chobs-sat

### ISSUE THREAD

**Issue by lecjlg** [cemac/SWIFT-Testbed3#42]
This is pretty messy due to all the development over the years 
The cronfile needs comments and the scripts need cleaning up and pushing back to the git repo.

**Comment by lecjlg** [comment]
current cron
CRON_TZ=UTC

# Edit this file to introduce tasks to be run by cron.
# 
# Each task to run has to be defined through a single line
# indicating with different fields when the task will be run
# and what command to run for the task
# 
# To define the time you can provide concrete values for
# minute (m), hour (h), day of month (dom), month (mon),
# and day of week (dow) or use '*' in these fields (for 'any').# 
# Notice that tasks will be started based on the cron's system
# daemon's notion of time and timezones.
# 
# Output of the crontab jobs (including errors) is sent through
# email to the user the crontab file belongs to (unless redirected).
# 
# For example, you can run a backup of all your user accounts
# at 5 a.m every week with:
# 0 5 * * 1 tar -zcf /var/backups/home.tgz /home/
# 
# For more information see the manual pages of crontab(5) and cron(8)
# 
# m h  dom mon dow   command

1-46/15 * * * * /opt/scripts/copy_sat_data
#1-46/15 * * * * /opt/scripts/tellicast_log.sh
* * * * * /opt/scripts/export_archive
1-59/2 * * * * /opt/scripts/run_all_plotting
0-58/2 * * * * /opt/scripts/move_images
0 12 * * * /data/NWCPY3/scripts/clean_command_list.sh
1-59/2 * * * * /data/NWCPY3/scripts/combine_HRW.sh
23 1 * * * /data/NWCPY3/scripts/copy_to_archive3.sh
14-59/15 * * * * /opt/scripts/NFLICS_create_netcdf.sh
#2-47/15 * * * * /opt/scripts/convert_RDT_GEOJSON.sh
#2-47/15 * * * * /opt/scripts/convert_CRR_GEOJSON.sh
0 0 * * * /opt/scripts/clean_NFLICS_archive.sh
*/10 * * * * /opt/scripts/archive_hrit_files
0 10 * * * /opt/scripts/archive_gfs
0 6 * * * /data/NWCPY3/scripts/sort_archive.sh
* * * * * /opt/scripts/copy_fasta_CRR
* * * * * /opt/scripts/copy_fasta_RDT

**Comment by lecjlg** [comment]
```
# 0 5 * * 1 tar -zcf /var/backups/home.tgz /home/
# 
# For more information see the manual pages of crontab(5) and cron(8)
# 
# m h  dom mon dow   command

#----NWCSAF file prep.
#-Decrypt the received HRIT files and move them into the import directory ready for NWCSAF to process
1-46/15 * * * * /opt/scripts/copy_sat_data

#---Plotting
#-Create the file list for plotting and run the pool
1-59/2 * * * * /opt/scripts/run_all_plotting
#-Clean up old command lists
0 12 * * * /data/NWCPY3/scripts/clean_command_list.sh

##--CEH create the files required by CEH and copy them off.
14-59/15 * * * * /opt/scripts/NFLICS_create_netcdf.sh
0 0 * * * /opt/scripts/clean_NFLICS_archive.sh

#----Copy files for the catalogue to Jasmin 
#-Move the png images to potts and swift-saf machine.
0-58/2 * * * * /opt/scripts/move_images
#-Copy the netcdf files to swift-plot for plotting in python. 
*/5 * * * * /opt/scripts/copy_netcdf_to_swift_plot

#----Fasta scripts
* * * * * /opt/scripts/copy_fasta_CRR
* * * * * /opt/scripts/copy_fasta_RDT

#----High rate winds script
#-No idea what this does need to ask Alex?
1-59/2 * * * * /data/NWCPY3/scripts/combine_HRW.sh

##---Archive scripts
#--files that are being archived locally on the machine to the data drive
#-Move gfs data to the data drive
0 10 * * * /opt/scripts/archive_gfs
#-Move the HRIT file to the data drive
*/10 * * * * /opt/scripts/archive_hrit_files
#-Move the netcdf files to the data drive
* * * * * /opt/scripts/export_archive

#--Archive files off the machine
#-Archive the netcdf files to Jasmin
23 1 * * * /data/NWCPY3/scripts/copy_to_archive3.sh
#-Archive the recieved HRIT files to Jasmin 
0 6 * * * /data/NWCPY3/scripts/sort_archive.sh

#---Old crons no longer used.
#2-47/15 * * * * /opt/scripts/convert_CRR_GEOJSON.sh
#2-47/15 * * * * /opt/scripts/convert_RDT_GEOJSON.sh
#1-46/15 * * * * /opt/scripts/tellicast_log.sh

```

**Comment by lecjlg** [comment]
Suggested change? above

**Comment by tdjames1** [comment]
Much clearer!
