### ISSUE TITLE
Add NFLICS products to the catalogue

### ISSUE THREAD

**Issue by lecjlg** [cemac/SWIFT-Testbed3#57]
CEH have started to upload their NFLICS data to the swift GWS. These will need to be catalogued in a similar way to the NWCSAF and MSG products. 

Again these will probably need a separate category creating.

**Comment by eardkdw** [comment]
NFLICS /CEH products added to test version of catalogue

**Comment by tdjames1** [comment]
There are quite a few more NFLICS plots that are not included at the moment: https://gws-access.jasmin.ac.uk/public/swift/TestBed3/ceh_plots/
@lecjlg has asked Chris to give us a steer on what products he wanted including.

**Comment by tdjames1** [comment]
Info from CEH:

> **NFLICS nowcast images**
> We have been adding data here:
> https://gws-access.jasmin.ac.uk/public/swift/TestBed3/ceh_plots/NFLICS_nowcasts/YYYY/MM/DD/hhmm/
> The nowcasts are made every 15 minutes.
> These are all on the NFLICS domain which is smaller than the NWC-SAF West Africa plots.
> These images are used in the NFLICS GUI at ANACIM. Summary of all is below but immediate priority, based on what Chris and Doug have been finding most useful, would be the following Probability of Convective Activity nowcasts:
> `Nowcast_v2_ YYYYMMDDhhmm_000_360.gif` (hourly time-step GIF out to 6 hours)
> `Nowcast_v2_ YYYYMMDDhhmm _120.png` (2 hour ahead nowcast)
> `Nowcast_v2_ YYYYMMDDhhmm _360.png` (6 hour ahead nowcast)
> Note the latest versions of these are stored here: 
> https://gws-access.jasmin.ac.uk/public/swift/TestBed3/ceh_plots/
> `latest_nowcast.gif`
> `latest_2hr_nowcast.png`
> `latest_6h_nowcast.png`
> Making the latest data easily viewable would be great as well as the archive in due course.
>
> Summary of other NFLICS files.
> 1. Current Land Surface Temperature anomaly and recent convective activity
> `LSTA_past_cores_YYYYMMDDhhmm_000.png` (one in each folder)
>  
> 2. Satellite observations of cloud top temperature and convective activity
> `Convective_struct_ YYYYMMDDhhmm _000.png` (one in each folder)
> Same process for identifying convective structures
>
> 3. Probability of Convective Activity Nowcast
> `Nowcast_v2_ YYYYMMDDhhmm_000_360.gif`
> 6 hour nowcast, hourly timestep, updated every 15 minutes.
> Constructed from hourly images
> `Nowcast_v2_ YYYYMMDDhhmm _000.png`
> `Nowcast_v2_ YYYYMMDDhhmm _060.png`
> `Nowcast_v2_ YYYYMMDDhhmm _120.png`
> `Nowcast_v2_ YYYYMMDDhhmm _180.png`
> `Nowcast_v2_ YYYYMMDDhhmm _240.png`
> `Nowcast_v2_ YYYYMMDDhhmm _300.png`
> `Nowcast_v2_ YYYYMMDDhhmm _360.png`
> Currently only 120 and 360 minute images on GWS but could add more.
>
> 4. Flood Risk nowcast
> Converts likelihood of convective activity, to likelihood of flood producing rainfall, and combines with likely impact. 
> `Risk_estimated_v2_YYYYMMDDhhmm_000.png` (one per nowcasts)

**Comment by eardkdw** [comment]
Resolved in Bitbucket commit [c3b288a](https://bitbucket.org/ncas_it/catalogue/commits/c3b288a8eda27d40b88b5311f838e3c61b718f4f)
