### ISSUE TITLE
Make it possible to edit category rank/summary flag for the swift-test database

### ISSUE THREAD

**Issue by tdjames1** [cemac/SWIFT-Testbed3#73]
@eardkdw Alex can't edit category rank for the swift-test database so won't be able to adjust ordering as desired until we've sorted that.

_Originally posted by @tdjames1 in https://github.com/cemac/SWIFT-Testbed3/issues/61#issuecomment-916244303_

**Comment by eardkdw** [comment]
Odd. You can save the Display Name but not the Display Order or the summery flag

**Comment by tdjames1** [comment]
Yes, that's what Alex reported.

**Comment by eardkdw** [comment]
As long as you edit the display name, you can edit the others at the same time....

**Comment by tdjames1** [comment]
Github does not offer the range of emojis required to respond appropriately...

**Comment by eardkdw** [comment]
Resolved in bitbucket commit  [36aba0f](https://bitbucket.org/ncas_it/catalogue/commits/36aba0fa25625bd89fedece65480ea954962218e)
