### ISSUE TITLE
Drop down links not working from single image view. 

### ISSUE THREAD

**Issue by lecjlg** [cemac/SWIFT-Testbed3#77]
The drop down menu for selecting an alternative image doesn't work from the single image view page.

Example. if you try and change to a different product from this view you get taken to an invalid URL. 
https://science.ncas.ac.uk/swift-test/resources/view/735768

You end up at a URL with no date 
https://science.ncas.ac.uk/swift-test/categories/nearest/61/%20UTC

**Comment by eardkdw** [comment]
Resolved in [swift-cakephp3-hotfix-issue77](https://bitbucket.org/ncas_it/catalogue/commits/branch/swift-cakephp3-hotfix-issue77) - will put live on Monday

**Comment by eardkdw** [comment]
Put live
