### ISSUE TITLE
Selecting a specific part of the link takes you back to the 70s 

### ISSUE THREAD

**Issue by lecjlg** [cemac/SWIFT-Testbed3#78]
There is a strange bug where if you select the number of files instead of the forecast time you get transported back to the time of bell-bottoms and the rise of disco!

On the link below click the 25 to see the error.
https://science.ncas.ac.uk/swift-test/categories/view/1181/2021-09-22

**Comment by eardkdw** [comment]
Resolved in pull request [#26](https://bitbucket.org/ncas_it/catalogue/pull-requests/26/swift-cakephp3-hotfix-issue78)

**Comment by eardkdw** [comment]
Put live.
